### ISSUE TITLE
Not const-correct

### ISSUE THREAD

**Issue by richelbilderbeek** [astrobiology/orca_array#1]
It appears orca_array does not follow many of the coding standards (see e.g. https://github.com/isocpp/CppCoreGuidelines ), one of them is that it the orca_array::array::length member functions are not const-correct. The code below does not compile, because getting the size of a 2D array is non-const.

```
#include <cassert>
#include "orca_array.hpp"

int main() {
  const int maxx{3};
  const int maxy{4};
  const orca_array::array2d<double> v(maxx,maxy);
  assert(v.length1() == maxx);
  assert(v.length2() == maxy);

}
```

**Comment by astrobiology** [comment]
Resolved. The orca_array length and at() member functions are now  const-correct. The above code now compiles and runs fine. Thanks!
